name: Node CI environment

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install & check src/
        run: |
          yarn
          yarn lint:dir src/
      - name: Bump release version
      - uses: christian-draeger/increment-semantic-version@1.0.2
        with:
          current-version: 'v1.0.3'
          version-fragment: 'feature'
      - name: Bump to next version
        run: echo ${{ steps.bump_version.outputs.next-version }}